name: property
channels:
    - pyviz
    - conda-forge
dependencies:
    - python=3.8
    - holoviz
    - geoviews
    - statsmodels
    - scikit-learn 
    - pyarrow
    - black
    - notebook
    - geopandas
    #- cartopy
    - geoplot
    - contextily
    - jupyterlab